### ISSUE TITLE
Out-Of-Memory crash during database upload

### ISSUE THREAD

**Issue by MHeinrichs** [DLR-TS/tsc#51]
Commiting a lagre simulation (100% Berlin) results in the following error on a 256GB-RAM machine:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "tsc_main.py", line 454, in simulation_request
    s2t_miv.upload_trip_results(conn, sim_key, params, final_routes)
  File "/usr/share/sumo/tools/sumolib/miscutils.py", line 41, in benchmark_wrapper
    result = func(*args, **kwargs)
  File "/mnt/SUMO/tsc2023/tsc/s2t_miv.py", line 154, in upload_trip_results
    cursor.execute(insertQuery % schema_table + ','.join(values))
psycopg2.errors.ProgramLimitExceeded: FEHLER:  Speicher aufgebraucht
DETAIL:  Kann Zeichenkettenpuffer mit 0 Bytes nicht um 1220878031 Bytes vergrößern.

suggested fix (txt instead of py) in lines 153-175:
[s2t_pt.txt](https://github.com/DLR-TS/tsc/files/10360601/s2t_pt.txt)

**Comment by behrisch** [comment]
The uploaded file contains the original (unchanged) source code

**Comment by behrisch** [comment]
We already had a try on using a dedicated postgres function here https://www.psycopg.org/docs/extras.html#fast-execution-helpers. I tried to re-enable this code, maybe it already helps
